In [1]:
import numpy as np

In [1]:
def concatenate_raw_data_dicts(patient_data_dict):
    concatenated_data = np.concatenate(list(patient_data_dict.values()), axis=0)
    return concatenated_data

In [2]:
def concatenate_raw_data_arrays(array1, array2):
    concatenated_data = np.concatenate([array1, array2], axis=0)
    return concatenated_data

In [8]:
# Example usage
patient_data_dict = {
    'Patient1': np.random.rand(22000, 15),
    'Patient2': np.random.rand(21000, 15),
    'Patient3': np.random.rand(20000, 15),
    # ... add more patients
}

concatenated_data = concatenate_raw_data_arrays(patient_data_dict)
print(concatenated_data)
print(np.shape(concatenated_data))

[[0.52523392 0.83429884 0.65104883 ... 0.20322783 0.98212855 0.3627328 ]
 [0.08716981 0.24056496 0.46956848 ... 0.85379949 0.98638723 0.47053219]
 [0.42810812 0.72362775 0.38927237 ... 0.13453209 0.0282137  0.58867784]
 ...
 [0.57479615 0.1140859  0.33519573 ... 0.90364369 0.42731787 0.90880347]
 [0.60801011 0.84571189 0.26873571 ... 0.08472095 0.24800288 0.62615304]
 [0.34380328 0.16410609 0.58437582 ... 0.68773461 0.94701422 0.75413061]]
(63000, 15)
